<?php

return array(
	'' => __( 'None', 'siteorigin-premium' ),
	'bounce' => __( 'Bounce', 'siteorigin-premium' ),
	'flash' => __( 'Flash', 'siteorigin-premium' ),
	'pulse' => __( 'Pulse', 'siteorigin-premium' ),
	'rubberBand' => __( 'Rubber band', 'siteorigin-premium' ),
	'shake' => __( 'Shake', 'siteorigin-premium' ),
	'swing' => __( 'Swing', 'siteorigin-premium' ),
	'tada' => __( 'Tada', 'siteorigin-premium' ),
	'wobble' => __( 'Wobble', 'siteorigin-premium' ),
	'jello' => __( 'Jello', 'siteorigin-premium' ),
	'bounceIn' => __( 'Bounce in', 'siteorigin-premium' ),
	'bounceInDown' => __( 'Bounce in down', 'siteorigin-premium' ),
	'bounceInLeft' => __( 'Bounce in left', 'siteorigin-premium' ),
	'bounceInRight' => __( 'Bounce in right', 'siteorigin-premium' ),
	'bounceInUp' => __( 'Bounce in up', 'siteorigin-premium' ),
	'fadeIn' => __( 'Fade in', 'siteorigin-premium' ),
	'fadeInDown' => __( 'Fade in down', 'siteorigin-premium' ),
	'fadeInDownBig' => __( 'Fade in down big', 'siteorigin-premium' ),
	'fadeInLeft' => __( 'Fade in left', 'siteorigin-premium' ),
	'fadeInLeftBig' => __( 'Fade in left big', 'siteorigin-premium' ),
	'fadeInRight' => __( 'Fade in right', 'siteorigin-premium' ),
	'fadeInRightBig' => __( 'Fade in right big', 'siteorigin-premium' ),
	'fadeInUp' => __( 'Fade in up', 'siteorigin-premium' ),
	'fadeInUpBig' => __( 'Fade in up big', 'siteorigin-premium' ),
	'flip' => __( 'Flip', 'siteorigin-premium' ),
	'flipInX' => __( 'Flip in horizontal', 'siteorigin-premium' ),
	'flipInY' => __( 'Flip in vertical', 'siteorigin-premium' ),
	'lightSpeedIn' => __( 'Light speed in', 'siteorigin-premium' ),
	'rotateIn' => __( 'Rotate in', 'siteorigin-premium' ),
	'rotateInDownLeft' => __( 'Rotate in down left', 'siteorigin-premium' ),
	'rotateInDownRight' => __( 'Rotate in down right', 'siteorigin-premium' ),
	'rotateInUpLeft' => __( 'Rotate in up left', 'siteorigin-premium' ),
	'rotateInUpRight' => __( 'Rotate in up right', 'siteorigin-premium' ),
	'slideInUp' => __( 'Slide in up', 'siteorigin-premium' ),
	'slideInDown' => __( 'Slide in down', 'siteorigin-premium' ),
	'slideInLeft' => __( 'Slide in left', 'siteorigin-premium' ),
	'slideInRight' => __( 'Slide in right', 'siteorigin-premium' ),
	'zoomIn' => __( 'Zoom in', 'siteorigin-premium' ),
	'zoomInDown' => __( 'Zoom in down', 'siteorigin-premium' ),
	'zoomInLeft' => __( 'Zoom in left', 'siteorigin-premium' ),
	'zoomInRight' => __( 'Zoom in right', 'siteorigin-premium' ),
	'zoomInUp' => __( 'Zoom in up', 'siteorigin-premium' ),
	'hinge' => __( 'Hinge', 'siteorigin-premium' ),
	'rollIn' => __( 'Roll in', 'siteorigin-premium' ),
);
